const data = {
  products: [
    {
      name: 'Nike shirt',
      slug: 'nike-slim-shirt',
      catogary: 'shirt',
      image: '/images/p1.jpg',
      price: 1200,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Adidas shirt',
      slug: 'adidas-slim-shirt',
      catogary: 'shirt',
      image: '/images/p2.jpg',
      price: 1300,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Puma shirt',
      slug: 'puma-slim-shirt',
      catogary: 'shirt',
      image: '/images/p3.jpg',
      price: 1450,
      countInStock: 10,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'LV shirt',
      slug: 'lv-slim-shirt',
      catogary: 'shirt',
      image: '/images/p4.jpg',
      price: 1100,
      countInStock: 10,
      brand: 'Louis Vitton',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
  ],
};

export default data;
